---
- name: install HID USB gadget
  import_tasks: install_usb_gadget.yml
  when: ansible_architecture.startswith("armv")

- name: install KVM Pi pre-requisite packages
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - git
      - python-pip
      - python3-venv
      - sudo

- name: create kvmpi group
  group:
    name: "{{ kvmpi_group }}"
    state: present

- name: create kvmpi user
  user:
    name: "{{ kvmpi_user }}"
    group: "{{ kvmpi_group }}"
    system: yes

- name: enable passwordless sudo for shutdown command
  lineinfile:
    dest: /etc/sudoers
    state: present
    line: "{{ kvmpi_user }} ALL=(ALL) NOPASSWD: /sbin/shutdown"

- name: create KVM Pi folder
  file:
    path: "{{ kvmpi_dir }}"
    state: directory
    owner: "{{ kvmpi_user }}"
    group: "{{ kvmpi_group }}"

- name: get KVM Pi repo
  git:
    repo: "{{ kvmpi_repo }}"
    dest: "{{ kvmpi_dir }}"
    version: "{{ kvmpi_repo_branch }}"
    accept_hostkey: yes
  notify:
    - restart KVM Pi service

- name: create KVM Pi virtualenv
  pip:
    virtualenv: "{{ kvmpi_dir }}/venv"
    virtualenv_command: python3 -m venv venv
    requirements: "{{ kvmpi_dir }}/requirements.txt"
  notify:
    - restart KVM Pi service

- name: fix KVM Pi folder permissions
  file:
    path: "{{ kvmpi_dir }}"
    state: directory
    owner: "{{ kvmpi_user }}"
    group: "{{ kvmpi_group }}"

- name: install KVM Pi as a service
  template:
    src: kvmpi.systemd.j2
    dest: /lib/systemd/system/kvmpi.service
    owner: root
    group: root
    mode: '0644'
  notify:
    - reload KVM Pi systemd config
    - restart KVM Pi service

- name: enable systemd KVM Pi service file
  systemd:
    name: kvmpi
    enabled: yes
