---
- name: install HID USB gadget
  import_tasks: install_usb_gadget.yml
  when: ansible_architecture.startswith("armv")

- name: install Tiny Pilot pre-requisite packages
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - git
      - python-pip
      - python3-venv
      - sudo

- name: create tinypilot group
  group:
    name: "{{ tinypilot_group }}"
    state: present

- name: create tinypilot user
  user:
    name: "{{ tinypilot_user }}"
    group: "{{ tinypilot_group }}"
    system: yes

- name: enable passwordless sudo for shutdown command
  lineinfile:
    dest: /etc/sudoers
    state: present
    line: "{{ tinypilot_user }} ALL=(ALL) NOPASSWD: /sbin/shutdown"

- name: create Tiny Pilot folder
  file:
    path: "{{ tinypilot_dir }}"
    state: directory
    owner: "{{ tinypilot_user }}"
    group: "{{ tinypilot_group }}"

- name: get Tiny Pilot repo
  git:
    repo: "{{ tinypilot_repo }}"
    dest: "{{ tinypilot_dir }}"
    version: "{{ tinypilot_repo_branch }}"
    accept_hostkey: yes
  notify:
    - restart Tiny Pilot service

- name: create Tiny Pilot virtualenv
  pip:
    virtualenv: "{{ tinypilot_dir }}/venv"
    virtualenv_command: python3 -m venv venv
    requirements: "{{ tinypilot_dir }}/requirements.txt"
  notify:
    - restart Tiny Pilot service

- name: fix Tiny Pilot folder permissions
  file:
    path: "{{ tinypilot_dir }}"
    state: directory
    owner: "{{ tinypilot_user }}"
    group: "{{ tinypilot_group }}"

- name: install Tiny Pilot as a service
  template:
    src: tinypilot.systemd.j2
    dest: /lib/systemd/system/tinypilot.service
    owner: root
    group: root
    mode: '0644'
  notify:
    - reload Tiny Pilot systemd config
    - restart Tiny Pilot service

- name: enable systemd Tiny Pilot service file
  systemd:
    name: tinypilot
    enabled: yes
