---
- name: import uStreamer role
  import_role:
    name: mtlynch.ustreamer
  vars:
    ustreamer_interface: '127.0.0.1'
    ustreamer_port: 8001
    ustreamer_repo: https://github.com/tiny-pilot/ustreamer.git
    ustreamer_repo_version: "v3.26"
